[package]
name = "crabmancake"
version = "0.1.0"
authors = ["Trenton Andres <trenton.andres@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = "0.1"
console_error_panic_hook = "0.1"
git-version = "0.3"
js-sys = "0.3"
log = "0.4"
thiserror = "1.0.20"
wasm-bindgen = "0.2"
lazy_static = "1.3.0"

[dependencies.web-sys]
version = "0.3"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'EventTarget',
  'HtmlElement',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlUniformLocation',
  'WebGlShader',
]
